//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class الأطباء
    {
        public int رمز_ { get; set; }
        public string C_اسم { get; set; }
        public string عنوان { get; set; }
        public string اختصاص { get; set; }
        public string هاتف { get; set; }
        public Nullable<int> مكان_العمل { get; set; }
        public Nullable<int> القسم { get; set; }
        public Nullable<int> رمز_المدينة { get; set; }
        public Nullable<int> رمز_المنطقة { get; set; }
    
        public virtual أقسام_المستشفيات أقسام_المستشفيات { get; set; }
        public virtual المستشفيات المستشفيات { get; set; }
        public virtual المدن المدن { get; set; }
        public virtual المناطق المناطق { get; set; }
    }
}
