//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class المهمات_المنفذة
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public المهمات_المنفذة()
        {
            this.الفريق = new HashSet<الفريق>();
        }
    
        public int الرمز_الشهري { get; set; }
        public int رمز_السنوي { get; set; }
        public int السنة { get; set; }
        public int رمز__المركز { get; set; }
        public Nullable<System.DateTime> التاريخ { get; set; }
        public Nullable<int> الآلية { get; set; }
        public Nullable<int> المريض { get; set; }
        public Nullable<int> الطبيب_المعالج { get; set; }
        public Nullable<int> رقم_المتصل { get; set; }
        public Nullable<int> متلقي_المهمة { get; set; }
        public string تفاصيل_ال_من { get; set; }
        public string تفاصيل_ال_الى { get; set; }
        public string التفاصيل { get; set; }
        public string اسم_المتصل { get; set; }
        public Nullable<int> طبيعة_المهمة { get; set; }
        public Nullable<bool> مريض_مقعد { get; set; }
        public Nullable<int> الأمراض_المعدية { get; set; }
        public Nullable<int> مسؤول_الدوام { get; set; }
        public Nullable<int> نوعية_الحالة { get; set; }
        public Nullable<int> من { get; set; }
        public Nullable<int> إلى { get; set; }
    
        public virtual الأطباء الأطباء { get; set; }
        public virtual الآليات الآليات { get; set; }
        public virtual الأمراض_المعدية الأمراض_المعدية1 { get; set; }
        public virtual العاملون العاملون { get; set; }
        public virtual العاملون العاملون1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<الفريق> الفريق { get; set; }
        public virtual المرضى المرضى { get; set; }
        public virtual إلى إلى1 { get; set; }
        public virtual طبيعة_المهمة طبيعة_المهمة1 { get; set; }
        public virtual من من1 { get; set; }
        public virtual نوعيات_الحالات نوعيات_الحالات { get; set; }
    }
}
