//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class المستشفيات
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public المستشفيات()
        {
            this.الأطباء = new HashSet<الأطباء>();
            this.المستشفيات_مع_اقسام = new HashSet<المستشفيات_مع_اقسام>();
        }
    
        public int رمز_المستشفى { get; set; }
        public string العنوان { get; set; }
        public string الهاتف { get; set; }
        public string اسم_المستشفى { get; set; }
        public Nullable<int> رمز_المنطقة { get; set; }
        public Nullable<short> الطابق_السفلي { get; set; }
        public Nullable<short> الطابق_العلوي { get; set; }
        public string الملاحظات { get; set; }
        public string الحالة { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<الأطباء> الأطباء { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<المستشفيات_مع_اقسام> المستشفيات_مع_اقسام { get; set; }
        public virtual المناطق المناطق { get; set; }
    }
}
