//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class حالات_المهمات
    {
        public int رمز_الحالة { get; set; }
        public int الرمز_الشهري { get; set; }
        public string رمز_السنوي { get; set; }
        public string السنة { get; set; }
    }
}
