//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class الفريق
    {
        public int الرمز_الشهري { get; set; }
        public int رمز_السنوي { get; set; }
        public int السنة { get; set; }
        public int رمز__المركز { get; set; }
        public int رمز_العامل { get; set; }
        public int دور_العامل { get; set; }
    
        public virtual الدور_في_المهمة الدور_في_المهمة { get; set; }
        public virtual العاملون العاملون { get; set; }
        public virtual المهمات_المنفذة المهمات_المنفذة { get; set; }
    }
}
