//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class المهمات_الملغاة
    {
        public int السنة { get; set; }
        public int الرمز_الشهري { get; set; }
        public int رمز_السنوي { get; set; }
        public Nullable<System.DateTime> التاريخ { get; set; }
        public Nullable<int> رمز_المريض { get; set; }
        public Nullable<int> من { get; set; }
        public Nullable<int> إلى { get; set; }
        public Nullable<int> تفاصيل_ال_من { get; set; }
        public Nullable<int> تفاصيل_ال_الى { get; set; }
        public Nullable<int> رمز_الحالة { get; set; }
        public Nullable<int> طبيعة_المهمة { get; set; }
    
        public virtual الحالات الحالات { get; set; }
        public virtual المرضى المرضى { get; set; }
        public virtual إلى إلى1 { get; set; }
        public virtual طبيعة_المهمة طبيعة_المهمة1 { get; set; }
        public virtual من من1 { get; set; }
    }
}
