//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class المهمات_المنفذة
    {
        public int الرمز_الشهري { get; set; }
        public Nullable<System.DateTime> التاريخ { get; set; }
        public Nullable<int> الآلية { get; set; }
        public int المريض { get; set; }
        public Nullable<int> من_مشفى { get; set; }
        public Nullable<int> من_القسم { get; set; }
        public Nullable<int> الطبيب_المعالج { get; set; }
        public Nullable<int> الجهة_الضامنة { get; set; }
        public Nullable<int> إلى_مشفى { get; set; }
        public Nullable<int> إلى_القسم { get; set; }
        public int مسؤول_المهمة { get; set; }
        public int مسعف_1 { get; set; }
        public int مسعف_2 { get; set; }
        public int السائق { get; set; }
        public Nullable<int> المتصل { get; set; }
        public string الهاتف { get; set; }
        public Nullable<int> متلقي_المهمة { get; set; }
        public int رمز_الحالة { get; set; }
        public string رمز_السنوي { get; set; }
        public int السنة { get; set; }
        public string تفاصيل_ال_من { get; set; }
        public string تفاصيل_ال_الى { get; set; }
        public Nullable<int> من_رمز_المدينة { get; set; }
        public Nullable<int> من_رمز_المنطقة { get; set; }
        public Nullable<int> الى_رمز_المدينة { get; set; }
        public Nullable<int> الى_رمز_المنطقة { get; set; }
        public string التفاصيل { get; set; }
        public string اسم_المتصل { get; set; }
        public int طبيعة_المهمة { get; set; }
        public string رمز__المركز { get; set; }
    
        public virtual أقسام_المستشفيات أقسام_المستشفيات { get; set; }
        public virtual أقسام_المستشفيات أقسام_المستشفيات1 { get; set; }
        public virtual الأطباء الأطباء { get; set; }
        public virtual الآليات الآليات { get; set; }
        public virtual الحالات الحالات { get; set; }
        public virtual العاملون العاملون { get; set; }
        public virtual العاملون العاملون1 { get; set; }
        public virtual العاملون العاملون2 { get; set; }
        public virtual العاملون العاملون3 { get; set; }
        public virtual العاملون العاملون4 { get; set; }
        public virtual المدن المدن { get; set; }
        public virtual المدن المدن1 { get; set; }
        public virtual المرضى المرضى { get; set; }
        public virtual المستشفيات المستشفيات { get; set; }
        public virtual المستشفيات المستشفيات1 { get; set; }
        public virtual المناطق المناطق { get; set; }
        public virtual المناطق المناطق1 { get; set; }
        public virtual طبيعة_المهمة طبيعة_المهمة1 { get; set; }
    }
}
