//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erc1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class الأطباء
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public الأطباء()
        {
            this.المرضى = new HashSet<المرضى>();
            this.المهمات_المنفذة = new HashSet<المهمات_المنفذة>();
        }
    
        public int رمز { get; set; }
        public string عنوان { get; set; }
        public string اختصاص { get; set; }
        public string هاتف { get; set; }
        public Nullable<int> مكان_العمل { get; set; }
        public Nullable<int> رمز_المدينة { get; set; }
        public Nullable<int> رمز_المنطقة { get; set; }
        public string اسم { get; set; }
    
        public virtual المدن المدن { get; set; }
        public virtual المناطق المناطق { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<المرضى> المرضى { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<المهمات_المنفذة> المهمات_المنفذة { get; set; }
        public virtual المستشفيات المستشفيات { get; set; }
    }
}
